name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "${{ matrix.python-version }}"
      - name: setup
        run: uv sync --dev
      - run: uv run coverage run -m unittest
        env:
          PYTHONWARNINGS: error
      - name: gather XML coverage data
        run: uv run coverage xml
      - uses: codecov/codecov-action@v5
  check:
    if: always()
    name: check-all

    needs:
      - test

    runs-on: Ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
